language: php

php:
  - 5.3

before_install:
  - sudo apt-get update > /dev/null

install:
  # install php packages required for running a web server from drush on php 5.3
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql

before_script:
  # navigate out of module directory to prevent blown stack by recursive module lookup
  - cd /home/travis/build

  - mkdir /home/travis/build/workspace 
  - cd /home/travis/build/workspace

  - git clone https://github.com/klausi/pareviewsh.git
  - git clone --branch phpcs-fixer https://github.com/squizlabs/PHP_CodeSniffer.git
  - git clone --branch 8.x-2.x http://git.drupal.org/project/coder.git
  - git clone --branch 8.x-1.x http://git.drupal.org/project/drupalpractice.git
  - git clone --branch master http://git.drupal.org/sandbox/coltrane/1921926.git drupalsecure
  - git clone --branch master https://github.com/lucasdemarchi/codespell.git

  - ln -s /home/travis/build/workspace/coder/coder_sniffer/Drupal /home/travis/build/workspace/PHP_CodeSniffer/CodeSniffer/Standards
  - ln -s /home/travis/build/workspace/drupalpractice/DrupalPractice /home/travis/build/workspace/PHP_CodeSniffer/CodeSniffer/Standards
  - ln -s /home/travis/build/workspace/drupalsecure/DrupalSecure /home/travis/build/workspace/PHP_CodeSniffer/CodeSniffer/Standards

  - sudo ln -s /home/travis/build/workspace/PHP_CodeSniffer/scripts/phpcs /usr/local/bin
  - sudo ln -s /home/travis/build/workspace/codespell/codespell.py /usr/local/bin/codespell

  - sudo ln -s /home/travis/build/workspace/pareviewsh/pareview.sh /usr/local/bin

  #/home/travis/build/workspace/pareviewsh/pareview.sh /home/travis/build/sergeypavlenko/travispareview/code

script: phpcs -p -s -v --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,js,css,info,txt,md /home/travis/build/sergeypavlenko/travispareview/code