language: php

php:
  - 5.3

before_install:
  - sudo apt-get update > /dev/null

install:
  # for codespell.
  - sudo apt-get install python3

before_script:
  - cd /home/travis/build

  - mkdir /home/travis/build/workspace 
  - cd /home/travis/build/workspace

  - git clone https://github.com/sergeypavlenko/pareviewsh.git
  - git clone --branch phpcs-fixer https://github.com/squizlabs/PHP_CodeSniffer.git
  - git clone --branch 8.x-2.x http://git.drupal.org/project/coder.git
  - git clone --branch 8.x-1.x http://git.drupal.org/project/drupalpractice.git
  - git clone --branch master http://git.drupal.org/sandbox/coltrane/1921926.git drupalsecure
  - git clone --branch master https://github.com/lucasdemarchi/codespell.git

  - ln -s /home/travis/build/workspace/coder/coder_sniffer/Drupal /home/travis/build/workspace/PHP_CodeSniffer/CodeSniffer/Standards
  - ln -s /home/travis/build/workspace/drupalpractice/DrupalPractice /home/travis/build/workspace/PHP_CodeSniffer/CodeSniffer/Standards
  - ln -s /home/travis/build/workspace/drupalsecure/DrupalSecure /home/travis/build/workspace/PHP_CodeSniffer/CodeSniffer/Standards

  - sudo ln -s /home/travis/build/workspace/PHP_CodeSniffer/scripts/phpcs /usr/local/bin
  - sudo ln -s /home/travis/build/workspace/codespell/codespell.py /usr/local/bin/codespell

  - sudo ln -s /home/travis/build/workspace/pareviewsh/pareview.sh /usr/local/bin

script:
  - phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,js,css,info,txt,md /home/travis/build/sergeypavlenko/travispareview/code
  - phpcs --standard=DrupalPractice --extensions=php,module,inc,install,test,profile,theme /home/travis/build/sergeypavlenko/travispareview/code
  - phpcs --standard=DrupalSecure --extensions=php,module,inc,install,test,profile,theme /home/travis/build/sergeypavlenko/travispareview/code
  - codespell -d /home/travis/build/sergeypavlenko/travispareview/code
  - /home/travis/build/workspace/pareviewsh/pareview.sh /home/travis/build/sergeypavlenko/travispareview/code
